### ISSUE TITLE
play.py broken, method implementation missing

### ISSUE THREAD

**Issue by dbischof90** [plietar/python-librespot#2]
`
Traceback (most recent call last):
  File "play.py", line 22, in <module>
    session.get_track(trackid).spawn(print_track)
AttributeError: 'PyFuture' object has no attribute 'spawn'
`

I get this while executing play.py with a track.
Looking at your pyfuture.rs, I noted the missing public function `spawn`.

**Comment by plietar** [comment]
Thanks, I used to have a `spawn` method when I was playing around with adding support for callbacks, and forgot to change the example back
